version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysqlDB
    restart: always
    environment:
      MYSQL_DATABASE: shoppersclues
      MYSQL_USER: shopuser
      MYSQL_PASSWORD: shop123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
